# Site settings
title: 캘리팩토리 기술 블로그
description: 일상적인 추천 서비스 개발 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://calyfactory.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: CalyFactory
user_description: SoftwareMaestro 7th Project 
email: calyfactory@gmail.com # TODO : 이메일 계정 만들기 
twitter_username: null
github_username:  CalyFactory
gplus_username:  null
disqus_username: null

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
